<?php 

	$helper = $this->helper('Magepow\promotionbar\Helper\Data');
	$showSlider = $helper->getConfigModule('magepow_promotionbar/general/showslider');
	$sliderControl = $block->getDataSliderControl();
	$speedSlider = $helper->getConfigModule('magepow_promotionbar/general/speedslider');
	$autoclose = $helper->getConfigModule('magepow_promotionbar/general/autoclose');
	$selector    = 'promotionbar-'.uniqid();
	$productPromotion = $block->getPromotionbarCollection();
	?>
<div data-mage-init='{"promotionbar": {}}'>
	<?php if($block->getRequest()->getFullActionName() == "cms_index_index"
	||$block->getRequest()->getFullActionName() == "checkout_cart_index"
	|| $block->getRequest()->getFullActionName() == "checkout_index_index") {?> 
<div data-role="promotion-collection" class="promotionbar promotionbar-topmenu <?php echo $selector ?>">
	<?php //$productPromotion = $block->getPromotionbarCollection(); ?>
	<?php foreach ($productPromotion as $value):?>
	
		<?php if($value->getPosition() == 2): ?>

	<div id="content 
	promotionbar-<?php echo ($value->getDisplayOnpage())?>
	-<?php echo ($value->getEntityId())?>"><?php echo $block->getContentFromStaticBlock($value->getPromotionbarInfo());?>
		
	</div>
		<?php endif; ?>
	<?php  endforeach; ?>
</div>
<?php 
	} 
?>

<?php if($block->getRequest()->getFullActionName() == "catalog_category_view") {
	?>
	<div data-role="promotion-collection"class="promotionbar promotionbar-topmenu <?php echo $selector ?>">
		<?php foreach ($productPromotion as $value):?>
			<?php if($value->getPosition() == 2):?>
		<?php	$category = $value->getCategory();
				$categoryArray = array($category);
				if(array_intersect(explode(",", $block->getCurrentCategory()),$categoryArray)):?>

	<div id="content promotionbar category-<?php echo ($value->getEntityId())?>"><?php echo $block->getContentFromStaticBlock($value->getPromotionbarInfo());?>
		
	</div>
		<?php endif;
				endif;?>
	<?php  endforeach; ?>
	</div>
<?php 
} 
?>
<?php if($block->getRequest()->getFullActionName() == "catalog_product_view") {
	$productPromotionbar = $block->getPromotionbarProduct();
	// if(! $productPromotion) return;
	// $promotionInfo = $productPromotion['promotionbar_info'];
	// // print_r($promotionInfo);
	// // exit();
	// $promotion = $productPromotion['conditions_serialized'];
	// print_r($promotion);
	// exit();
	// $position = $productPromotion['position'];
	
	//if($position == 2){
	?>
	<div data-role="promotion-collection"class="promotionbar promotionbar-topmenu <?php echo $selector ?>">
		<?php foreach ($productPromotion as $value):?>
		<?php if($value->getPosition() == 2): ?>
				<?php $config = $block->PromotionbarInfo($value->getEntityId()); ?>
				<?php $parameters = array($config['parameters']);?>
				<?php if(in_array($productPromotionbar,$parameters)):?>
				
	<div id="content <?php echo ($value->getPosition())?>"><?php echo $block->getContentFromStaticBlock($value->getPromotionbarInfo());?>
		
	</div>
<?php endif; ?>
	<?php endif; ?>
	<?php endforeach; ?>

</div>



<?php } 

//}
?>



</div>
<script type="text/x-magento-init">
        {
            "[data-role=promotion-collection]": {
                "Magepow_Promotionbar/js/common": {
                    "showSlider": <?=  $showSlider ?>,
                    "sliderControl": <?= $sliderControl ?>,
                    "speedSlider": <?= $speedSlider ?>
                   
                }
            }
        }
    </script> 

