<?php 

	$helper = $this->helper('Magepow\promotionbar\Helper\Data');
	$showSlider = $helper->getConfigModule('magepow_promotionbar/general/showslider');
	$sliderControl = $block->getDataSliderControl();
	$speedSlider = $helper->getConfigModule('magepow_promotionbar/general/speedslider');
	$autoclose = $helper->getConfigModule('magepow_promotionbar/general/autoclose');
	$selector    = 'promotionbar-'.uniqid();
	$productPromotion = $block->getPromotionbarCollection();

	?>
<div data-mage-init='{"promotionbar": {}}'>

	<?php if($block->getRequest()->getFullActionName() == "cms_index_index"
	||$block->getRequest()->getFullActionName() == "checkout_cart_index"
	|| $block->getRequest()->getFullActionName() == "checkout_index_index") {?> 
<div data-role="promotion-collection"class="promotionbar promotionbar-topcontent <?php echo $selector ?>">
	
	<?php  ?>
	<?php foreach ($productPromotion as $value):?>
	
		<?php if($value->getPosition() == 1): ?>

	<div id="content <?php echo ($value->getPosition())?>-<?php echo ($value->getEntityId())?>"><?php echo $block->getContentFromStaticBlock($value->getPromotionbarInfo());?>
		
	</div>
	<?php endif; ?>
	<?php  endforeach; ?>
	</div>
<?php } ?>
<?php if($block->getRequest()->getFullActionName() == "catalog_category_view") {
	?>
	<div data-role="promotion-collection"class="promotionbar promotionbar-topcontent <?php echo $selector ?>">
		<?php foreach ($productPromotion as $value):?>
			<?php if($value->getPosition() == 1):?>
			<?php $category = $value->getCategory();
			$categoryArray = array($category);
			if(array_intersect(explode(",", $block->getCurrentCategory()),$categoryArray)): ?>
			
	<div id="content <?php echo ($value->getPosition())?>-<?php echo ($value->getEntityId())?>"><?php echo $block->getContentFromStaticBlock($value->getPromotionbarInfo());?>
		
	</div>
	<?php endif;
			endif;
	?>
	<?php  endforeach; ?>
</div>
<?php 
}
?>
<?php if($block->getRequest()->getFullActionName() == "catalog_product_view") {
	$productPromotionbar = $block->getPromotionbarProduct();
	//print_r($productPromotionbar);exit();	
	
	?>
	<div data-role="promotion-collection"class="promotionbar promotionbar-topcontent <?php echo $selector ?>">
		<?php foreach ($productPromotion as $value):?>
			<?php 
			if($value->getPosition() == 1): ?>
				<?php $config = $block->PromotionbarInfo($value->getEntityId());
				$parameters = array($config['parameters']);
				if(in_array($productPromotionbar,$parameters)):?>
				
			 
	<div id="content <?php echo ($value->getPosition())?>"><?php echo $block->getContentFromStaticBlock($value->getPromotionbarInfo());?>		
	</div>

		<?php 
		endif;
			endif;
		?>
<?php endforeach;?>
</div>
<?php 
	} 
?>
</div>
<script type="text/x-magento-init">
        {
            "[data-role=promotion-collection]": {
                "Magepow_Promotionbar/js/common": {
                    "showSlider": <?=  $showSlider ?>,
                    "sliderControl": <?= $sliderControl ?>,
                    "speedSlider": <?= $speedSlider ?>
                   
                }
            }
        }
    </script>  
